language: generic

env:
  global:
    - ENCRYPTION_LABEL="eaa0f98d3fae"
    - CHECKER_PARAMS='\&filterpattern=Text%20run%20is%20not%20in%20Unicode%20Normalization%20Form%20C\.\|.*appears%20to%20be%20written%20in.*\|.*Charmod%20C073.*'
script:
  - bash ./deploy.sh
notifications:
  email:
    on_success: never
    on_failure: always
