language: generic

env:
  global:
    - ENCRYPTION_LABEL="eaa0f98d3fae"
    - DEPLOY_USER="annevankesteren"
    - EXTRA_FILES="*.txt *.json *.css"
    - POST_BUILD_STEP="python visualize.py \"$DIR/\""

script:
  - curl --remote-name --fail https://resources.whatwg.org/build/deploy.sh && bash ./deploy.sh

notifications:
  email:
    on_success: never
    on_failure: always
